# Generated by Django 6.0.1 on 2026-05-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myImage_src')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
